---
title: "COVID 19 Analysis"
author: "Amitavo Ganguli"
date: "2022-11-29"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

```{r get_jhu_data}

base_url <- 'https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/'
files <- c('time_series_covid19_confirmed_US.csv', 'time_series_covid19_confirmed_global.csv', 'time_series_covid19_deaths_US.csv', 'time_series_covid19_deaths_global.csv', 'time_series_covid19_recovered_global.csv')
urls <- str_c(base_url, files)
uid_lookup_url <- 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv'
```

```{r read_data}

US_cases <- read_csv(urls[1])
global_cases <- read_csv(urls[2])
US_deaths <- read_csv(urls[3])
global_deaths <- read_csv(urls[4])
global_recovered <- read_csv(urls[5])
UID <- read_csv(uid_lookup_url)

```
```{r tidy_global_data}

global_cases <- global_cases %>% 
  pivot_longer(cols = -c(`Province/State`, `Country/Region`, Lat, Long),
               names_to = "date",
               values_to = "cases") %>%
  select(-c(Lat, Long))

global_deaths <- global_deaths %>% 
  pivot_longer(cols = -c(`Province/State`, `Country/Region`, Lat, Long),
               names_to = "date",
               values_to = "deaths") %>%
  select(-c(Lat, Long))

global <- global_cases %>%
  full_join(global_deaths) %>%
  rename(Country_Region = `Country/Region`, Province_State = `Province/State`) %>%
  mutate(date = mdy(date))

global <- global %>% filter(cases > 0)

```

```{r global_sanity_check}

summary(global)

global %>% filter(cases > 98000000)

```

```{r tidy_us_data}

US_cases <- US_cases %>% 
  pivot_longer(cols = -(UID:Combined_Key),
               names_to = "date",
               values_to = "cases") %>%
  select(Admin2:cases) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long_))

US_deaths <- US_deaths %>% 
  pivot_longer(cols = -(UID:Population),
               names_to = "date",
               values_to = "deaths") %>%
  select((Admin2:deaths)) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long_))

US <- US_cases %>%
  full_join(US_deaths)


```

```{r massage_global}

global <- global %>%
  unite("Combined_Key",
        c(Province_State, Country_Region),
        sep = ", ",
        na.rm = TRUE,
        remove = FALSE
        )

global <- global %>%
  left_join(UID, by = c('Province_State', 'Country_Region')) %>%
  select(-c(UID, FIPS)) %>%
  select(Province_State, Country_Region, date, cases, deaths, Population, Combined_Key)

```

```{r analyze}

US_by_state <- US %>%
  group_by(Province_State, Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>%
  mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
  select(Province_State, Country_Region, date, cases, deaths, deaths_per_mill, Population) %>%
  ungroup()

US_totals <- US_by_state %>%
  group_by(Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>%
  mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
  select(Country_Region, date, cases, deaths, deaths_per_mill, Population) %>%
  ungroup()

```

```{r vizualize_us}

US_totals %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date, y = cases)) +
  geom_line(aes(color = "cases")) +
  geom_point(aes(color = "cases")) +
  geom_line(aes(y = deaths, color = "deaths")) +
  geom_point(aes(y = deaths, color = "deaths")) + 
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title = "COVID19 in US", y=NULL)

```
```{r vizualize_ny}
state <- "New York"
US_by_state %>%
  filter(Province_State == state) %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date, y = cases)) +
  geom_line(aes(color = "cases")) +
  geom_point(aes(color = "cases")) +
  geom_line(aes(y = deaths, color = "deaths")) +
  geom_point(aes(y = deaths, color = "deaths")) + 
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title = str_c("COVID19 in ", state), y=NULL)

```

```{r more_analysis}
US_by_state2 <- US_by_state %>%
  mutate(new_cases = cases - lag(cases), new_deaths = deaths - lag(deaths))

US_totals2 <- US_totals %>%
  mutate(new_cases = cases - lag(cases), new_deaths = deaths - lag(deaths))
```

```{r vizualize_us2}

US_totals2 %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_line(aes(color = "new_cases")) +
  geom_point(aes(color = "new_cases")) +
  geom_line(aes(y = new_deaths, color = "new_deaths")) +
  geom_point(aes(y = new_deaths, color = "new_deaths")) + 
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title = "COVID19 in US", y=NULL)

```

```{r vizualize_ny2}
state <- "New York"
US_by_state2 %>%
  filter(Province_State == state) %>%
  ggplot(aes(x = date, y = new_cases)) +
  geom_line(aes(color = "new_cases")) +
  geom_point(aes(color = "new_cases")) +
  geom_line(aes(y = new_deaths, color = "new_deaths")) +
  geom_point(aes(y = new_deaths, color = "new_deaths")) + 
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title = "COVID19 in NY", y=NULL)

```

```{r state_totals_analysis}
US_state_totals <- US_by_state2 %>%
  group_by(Province_State) %>%
  summarize(deaths = max(deaths), cases = max(cases), population = max(Population), cases_per_thou = 1000*cases / population,
            deaths_per_thou = 1000*deaths / population) %>%
  filter(cases > 0, population > 0)

US_state_totals %>% slice_min(deaths_per_thou, n = 10)
US_state_totals %>% slice_max(deaths_per_thou, n = 10)

```


```{r  model}

mod <- lm(deaths_per_thou ~ cases_per_thou, data = US_state_totals)

summary(mod)

x_grid <- seq(1, 450)
new_df <- tibble(cases_per_thou = x_grid)
US_tot_w_pred <- US_state_totals %>% mutate(pred = predict(mod))
US_tot_w_pred

```

```{r  vizualize_model}

US_tot_w_pred %>% ggplot() +
  geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") +
  geom_point(aes(x = cases_per_thou, y = pred), color = "red")

```


